### ISSUE TITLE
Set shadow or elevation for SeriesItem

### ISSUE THREAD

**Issue by hrsalehi** [bmarrdev/android-DecoView-charting#19]
Is it possible to set shadow or elevation for ```SeriesItem``` ?

**Comment by bmarrdev** [comment]
Currently it is not possible to set a series elevation or shadow for a DecoView `SeriesItem`. However It may be simple to modify the canvas rendering engine of DecoView to first draw a shadow.  I will investigate some more when I have the time. If you could attach a couple of images showing how you would expect the shadow to look that would be helpful.

As a workaround in the current version I was able to achieve a result as shown in the attached image.

![screenshot_20160428-081010](https://cloud.githubusercontent.com/assets/10645191/14869920/f70b9e14-0d19-11e6-8c17-7dbc710c4afa.png)

This was done by creating a second DecoView (not just another series, but creating another DecoView view on the layout.

```
         <com.hookedonplay.decoviewlib.DecoView
            xmlns:custom="http://schemas.android.com/apk/res-auto"
            custom:dv_lineWidth="30dp"
            android:id="@+id/dynamicArcView2"
            android:paddingTop="6dp"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
        
        <com.hookedonplay.decoviewlib.DecoView
            xmlns:custom="http://schemas.android.com/apk/res-auto"
            custom:dv_lineWidth="28dp"
            android:id="@+id/dynamicArcView1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingBottom="6dp"/>
```
The shadow DecoView must be declared first in the XML so the second series is drawn on top. The shadow view has padding on the top and the main view has padding on the bottom.

Then whenever an event is triggered for the main view you need to also send the same event to the shadow.

 ```
       mDecoView1.addEvent(new DecoEvent.Builder(42.4f)
                .setIndex(mDecoView1Series1Index)
                .setDelay(3250)
                .build());

        mDecoView2.addEvent(new DecoEvent.Builder(42.4f)
                .setIndex(mDecoView2Series1Index)
                .setDelay(3250)
                .build());
```

**Comment by hrsalehi** [comment]
Some days ago I saw a prototype picture of some design in [Materialup.com](http://www.materialup.com) and I felt that I can make it with your library. The only problem is that I couldn't add some shadow to materialize my design.

![fitness v2](https://cloud.githubusercontent.com/assets/6253428/14878215/5baf98b2-0d37-11e6-89a6-3a7920030eba.png)

**Comment by bmarrdev** [comment]
Thanks for the image. The shadows do look really nice in the image you posted.

I think I can add an option to DecoView to show a blur shadow for any given series.

I only worry about the performance of creating the shadow dynamically as the series are rendered. This is a two fold hit on performance. Creating the blurred shadow takes extra time and the canvas needs to be rendered every 16ms to avoid jank.  The second hit is the BlurFilterMask provided by Android does not support hardware acceleration, so this would have to be turned off for the DecoView when using shadows.  Having said all that, it should still be possible. If I get a chance this weekend I will implement it and let you know how it performs on low spec hardware.

**Comment by hrsalehi** [comment]
Is there any way to put shadow on the widget itself like elevation. I mean you don't render shadow by yourself but make android create shadow by Its libraries. Maybe if you extends some class ( I don't know which maybe looking into design support library would help)

**Comment by hrsalehi** [comment]
I found a library that implemented shadow for Its graphs. Although he named It as progress view not chart but It can be used as an circular or ring charts. It doesn't have animations like you implemented but I tought maybe It can help your for shadow problem

https://github.com/GIGAMOLE/ArcProgressStackView

**Comment by bmarrdev** [comment]
I have done some testing with the shadows implemented. Like I suspected there is a bit of a performance hit, but that only becomes noticeable when animating say 5 - 10 series concurrently with the shadows applied. The good news is that for most use cases the performance will not be compromised.

I will add the ability to apply shadows into DecoView and try to find some time this week to release a beta v1.1 with this feature included.
 
Here is a sample snapshot, I think shadows will be a fantastic addition

![screenshot_2016-05-02-08-32-28](https://cloud.githubusercontent.com/assets/10645191/14944768/90bcac18-1041-11e6-96e3-66b258155a77.png)

**Comment by bmarrdev** [comment]
I have an initial basic implementation of the shadows feature for DecoView.

Here is how to use it:

Firstly you need to update your build.gradle to include this latest snapshot on the Shadow branch of DecoView.  

`compile 'com.github.bmarrdev:android-DecoView-charting:Shadow-SNAPSHOT'`

Then in your java source code.

```
        mDecoView = (DecoView) findViewById(R.id.dynamicArcView);
        mDecoView.disableHardwareAccelerationForDecoView();

        final SeriesItem seriesItem = new SeriesItem.Builder(Color.parseColor("#FFFF8800"))
                .setRange(0, mSeriesMax, 0)
                .setInset(new PointF(30, 30))
                .setShadowSize(30)
                .setShadowColor(Color.DKGRAY)
                .setInitialVisibility(false)
                .build();
```

There are two new functions added to the SeriesItem builder.
`setShadowSize(float shadowSize)`

Pass the number of pixels the shadow should extend from the edge of the series item.

`setShadowColor(int color)`

Pass the color of the shadow. If you don't set a color then the default is Color.BLACK.

There are two other very important notes about using shadows in DecoView.

You **must** call `DecoView.disableHardwareAccelerationForDecoView();` to disable hardware acceleration. The shadow functionality built into the Android canvas operations do not support the shadowing functionality.

If you are setting a shadow you will most likely want to also add the size of your shadow to the inset of the series item. The reason for this is the the decoView cannot draw outside of the given canvas. If you don't inset your series then at the middle edges of the view the shadow will be clipped. In the code sample about you can see I set the shadow size to 30 and also inset the series item 30 to prevent the shadow from being clipped. I was going to automatically inset any series with a shadow by the amount of the shadow, however this would result in multiple series not lining up on top of each other as expected if they have differing sized shadows. 

I hope this matches your requirements and feel free to add any feedback regarding the shadows implementation.

**Comment by hrsalehi** [comment]
Thank you very much It is very nice

**Comment by bmarrdev** [comment]
No worries, I should have an update out in the next week

**Comment by hrsalehi** [comment]
First thank you for 1.1 update.
Yesterday I test the shadow feature but the result was not good enough. There was an obvious lag in the animation (I think because of disabling hardwareAcceleration) at last I disabled the shadow for now. May be my activity has to much progress in It.

**Comment by bmarrdev** [comment]
Thanks for the feedback. Yeah generating alpha shadows on dynamically changing objects is very intensive. The shadows work much better on static objects. I don't know of any quick fix to increase the rendering performance.

**Comment by younagendra** [comment]
Hi, it was a nice feature to add. I was wondering how we could update the textview with a particular value.
Example: I want to update the calorie value 2,925 by passing to the listener, how can I update the value from 0 to 2,925.

**Comment by hrsalehi** [comment]
If you want to animate changing the text from 0 to 2,925 probably you can use ```TextSwitcher``` in android.
