### ISSUE TITLE
DuplicateFileException

### ISSUE THREAD

**Issue by HassankSalim** [bmarrdev/android-DecoView-charting#23]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'. > com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.nineoldandroids/library/pom.properties 	File1: C:\Users\Hassan\.gradle\caches\modules-2\files-2.1\com.nineoldandroids\library\2.4.0\e9b63380f3a242dbdbf103a2355ad7e43bad17cb\library-2.4.0.jar 	File2: C:\Users\Hassan\AndroidStudioProjects\excel2016\app\build\intermediates\exploded-aar\com.specyci\residemenu\1.6\jars\libs\nineoldandroids-library-2.4.0.jar

**Comment by bmarrdev** [comment]
I have removed NineOldAndroids from Deco (on a branch currently) as (a) It is a deprecated library, (b) I don't believe DecoView should still be supporting Android 2.x.

To use the latest version and avoid the conflict your experienced change your Gradle dependency to: 

`compile 'com.github.bmarrdev:android-DecoView-charting:PlatformAnimation-SNAPSHOT'`

These changes will be merged back into the master branch in the future.
