### ISSUE TITLE
Large load on CPU

### ISSUE THREAD

**Issue by stfbee** [bmarrdev/android-DecoView-charting#31]
When i show fragment with DecoView with simple animation for the first time, CPU load in android monitor jumps to 25%. I think, it is normal, but CPU load doesn't drop down after DecoView animation has canceled. On the contrary, CPU load continues to grow.

**Comment by bmarrdev** [comment]
I do not see the same issue on the sample apps. As soon as the animation finished I see the CPU drop back to 0. Can you provide more information or a small sample that reproduces the issue?

**Comment by stfbee** [comment]
Oh, problem was in another library (BlurKit), sorry for troubling
