### ISSUE TITLE
TextView

### ISSUE THREAD

**Issue by habibhermes** [bmarrdev/android-DecoView-charting#34]
Hi, please i want to know how to display the current value at the center of the circle. Do i have to add a textview to my layout? And if yes, how to make it to appear at the center of the circle. Thank you

**Comment by bmarrdev** [comment]
Yes, you need to add a `TextView` to your layout. You can then add listeners to update the value.

Take a look at the [layout in FauxFit](
https://github.com/bmarrdev/fauxfit-decoview-sample/blob/master/app/src/main/res/layout/activity_faux_fit.xml) for an example. This example uses a `RelativeLayout` containing the `DecoView` and a `TextView` centered in the `RelativeLayout`.
