### ISSUE TITLE
Manifest Merger issues

### ISSUE THREAD

**Issue by bogdanzurac** [bmarrdev/android-DecoView-charting#7]
Hey there. Cool library. Unfortunately, I cannot use it, as your Android Manifest contains "allowBackup" and "label" attrs, which conflict with the ones in our app. Now don't worry, this is mainly caused by an issue in the gradle Manifest Merger, as it doesn't accept the replace function for replacing those attrs.

However, until the issue inside gradle is fixed, could you push a build with those attrs removed so that we can use your library? I hardly think a library needs the allowBackup attr, even the label one.

**Comment by bmarrdev** [comment]
I reproduced this issue as you described and removed the allowBackup and label attributes as they are not relevant to the library. I have pushed a new version to the repository with just this change and confirmed it resolves the issue. Update your gradle script to include `compile 'com.github.bmarrdev:android-DecoView-charting:v0.9.5'`.

**Comment by bogdanzurac** [comment]
Working like a charm, thanks a lot for the quick response!
